### ISSUE TITLE
參數錯誤

### ISSUE THREAD

**Issue by oreowork** [shadowjohn/mycomicbus_cli#1]
請問修正算法是因為網站修改了顯示參數嗎？

另一方面請問是通過怎樣的形式去獲取下一頁的圖片呢？我測試了好久一直報錯，是我參數錯誤嗎？謝謝

我是使用mycomicbus_cli.exe test ，但是一直顯示下面的錯誤信息

### 
Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at mycomicbus_cli.Program.Main(String[] args)
###

**Comment by shadowjohn** [comment]
待我研究一下~~

**Comment by shadowjohn** [comment]
![image](https://user-images.githubusercontent.com/1788472/124558199-eda85b80-de6c-11eb-9d26-7bc4e84b5799.png)
oreowork您好，
感謝您的回饋，已修正了~

**Comment by shadowjohn** [comment]
> 請問修正算法是因為網站修改了顯示參數嗎？
> 
> 另一方面請問是通過怎樣的形式去獲取下一頁的圖片呢？我測試了好久一直報錯，是我參數錯誤嗎？謝謝
> 
> 我是使用mycomicbus_cli.exe test ，但是一直顯示下面的錯誤信息
> 
> Unhandled Exception: System.FormatException: Input string was not in a correct format.
> at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
> at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
> at System.Convert.ToInt32(String value)
> at mycomicbus_cli.Program.Main(String[] args)

修正嘍^^
comicbus 網站 js 語法有調整，拆成了二段，還加了一些跟 localStorage 語法，早期 Microsoft VSA Engine 裡沒有這類的函式
加上相容性寫法避掉，結果就能出現了

**Comment by oreowork** [comment]
> > 請問修正算法是因為網站修改了顯示參數嗎？
> > 另一方面請問是通過怎樣的形式去獲取下一頁的圖片呢？我測試了好久一直報錯，是我參數錯誤嗎？謝謝
> > 我是使用mycomicbus_cli.exe test ，但是一直顯示下面的錯誤信息
> > Unhandled Exception: System.FormatException: Input string was not in a correct format.
> > at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
> > at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
> > at System.Convert.ToInt32(String value)
> > at mycomicbus_cli.Program.Main(String[] args)
> 
> 修正嘍^^
> comicbus 網站 js 語法有調整，拆成了二段，還加了一些跟 localStorage 語法，早期 Microsoft VSA Engine 裡沒有這類的函式
> 加上相容性寫法避掉，結果就能出現了

哇，你動作好快速！謝謝你的修正，我一直以為是我的電腦缺少了什麼插件之類的，所以給你發了信息，謝謝你！
你寫的真棒，讓我可以保留自己喜歡的漫畫!
謝謝你！

**Comment by oreowork** [comment]
![image](https://user-images.githubusercontent.com/52243223/124559229-141ac680-de6e-11eb-8b85-13ab6ed419ef.png)

測試好了，問題已經修復了，簡單快速！

**Comment by shadowjohn** [comment]
其他本本不知道會不會出問題，有遇到再修~
