### ISSUE TITLE
Input string was not in a correct format. 參數錯誤

### ISSUE THREAD

**Issue by oreowork** [shadowjohn/mycomicbus_cli#2]
您好，又打擾了。
今天打算下最新的漫畫收藏發現又不能用了。

其實有源碼我也看不懂，請問是需要哪方面相關的知識才能幫助更新？

抱歉（太小白） + 謝謝 ！

**Comment by shadowjohn** [comment]
其實就是要破解他的javascript怎麼反解圖片路徑

**Comment by shadowjohn** [comment]
我研究一下~

**Comment by shadowjohn** [comment]
好像是官網換網址了
https://comicbus.live/online/a-18838.html?ch=1   (原本的)
https://comicabc.com/online/new-18838.html?ch=1 (新的)

**Comment by shadowjohn** [comment]
![image](https://user-images.githubusercontent.com/1788472/133966149-d48853b2-4088-4a5b-a4f4-e79d23f9b69c.png)
修了，您再試看看

**Comment by shadowjohn** [comment]
1、官方換了網址
2、然後他們網站加了幾行 jquery 跑了一些無用的code，之前沒有
3、似乎多了二行應該是在跑廣告的語法，而且還作了字串保護
document.writeln("<scr"+"ipt src='/js/adsview.js?p=bom1&r="+Math.random()+"'></scr"+"ipt>");
document.writeln("<scr"+"ipt src='/js/adsview.js?p=bom2&r="+Math.random()+"'></scr"+"ipt>");

作法就是順著他的 js 跑一次，這是本次的更新紀錄
https://github.com/shadowjohn/mycomicbus_cli/commit/01a5a67d4959da28a8dd8160dae6949eadb24d55#diff-0b69b473fe937040615d69f606751f61ddbc2e3a1849360ff2456c22afe88c0b

如果跑失敗，就把變數 sc 存成文字檔，實際在網頁 debug 模試跑看看

最後再跑迴圈把需要反解的「張數」反解，跑一個小迴圈
https://github.com/shadowjohn/mycomicbus_cli/blob/main/Program.cs
小迴圈在144行開始


總之就是他們後台在存照片有固定的公式
然後前端也要用同樣的公式反解路徑
理解公式困難，所以就把反解公式的部分，直接用 C# Microsoft.JScript.Vsa.VsaEngine
去執行網站的 js 語法，把跟路徑有關的部分抓出來跑看看
能反解能爬到圖就是贏^^"

如果他們不讓 js 去跑公式反解圖片路徑，那就變成圖台放的位置直接就被看光光
通常這種情況就要綁 referer、作 session 但都很容易破解，看的到就拿的到

把公式寫在 js 還算是不錯的一招

至於程式為什麼會這樣寫，為了有好看的漫畫，身體不由自主的就會寫了 XD

**Comment by oreowork** [comment]
> 1、官方換了網址
> 2、然後他們網站加了幾行 jquery 跑了一些無用的code，之前沒有
> 3、似乎多了二行應該是在跑廣告的語法，而且還作了字串保護
> document.writeln("<scr"+"ipt src='/js/adsview.js?p=bom1&r="+Math.random()+"'></scr"+"ipt>");
> document.writeln("<scr"+"ipt src='/js/adsview.js?p=bom2&r="+Math.random()+"'></scr"+"ipt>");
> 
> 作法就是順著他的 js 跑一次，這是本次的更新紀錄
> [01a5a67#diff-0b69b473fe937040615d69f606751f61ddbc2e3a1849360ff2456c22afe88c0b](https://github.com/shadowjohn/mycomicbus_cli/commit/01a5a67d4959da28a8dd8160dae6949eadb24d55#diff-0b69b473fe937040615d69f606751f61ddbc2e3a1849360ff2456c22afe88c0b)
> 
> 如果跑失敗，就把變數 sc 存成文字檔，實際在網頁 debug 模試跑看看
> 
> 最後再跑迴圈把需要反解的「張數」反解，跑一個小迴圈
> https://github.com/shadowjohn/mycomicbus_cli/blob/main/Program.cs
> 小迴圈在144行開始
> 
> 總之就是他們後台在存照片有固定的公式
> 然後前端也要用同樣的公式反解路徑
> 理解公式困難，所以就把反解公式的部分，直接用 C# Microsoft.JScript.Vsa.VsaEngine
> 去執行網站的 js 語法，把跟路徑有關的部分抓出來跑看看
> 能反解能爬到圖就是贏^^"

之前我的想法是
https://comicabc.com/online/new-18977.html?ch=1-2
https://comicabc.com/online/new-18977.html?ch=1-3
這樣一個一個的獲取，但是效率太低效了，一直到我看到你的github，發現你的效率太高效了，有打開你的源碼查看，但是就是不明白

> 
> 如果他們不讓 js 去跑公式反解圖片路徑，那就變成圖台放的位置直接就被看光光
> 通常這種情況就要綁 referer、作 session 但都很容易破解，看的到就拿的到
> 
> 把公式寫在 js 還算是不錯的一招

是不是整個的精華就在js？
> 
> 至於程式為什麼會這樣寫，為了有好看的漫畫，身體不由自主的就會寫了 XD

![image](https://user-images.githubusercontent.com/52243223/133974427-8bd6f12a-73ff-4b1a-a337-fe120285e595.png)

你好！
感謝你那麼快就修復了！我剛剛測試了，已經是可以用了。

**Comment by shadowjohn** [comment]
![image](https://user-images.githubusercontent.com/1788472/134001096-2f583b70-cce6-4743-908e-ec608e102c55.png)
