### ISSUE TITLE
Input string was not in a correct format. 參數錯誤 

### ISSUE THREAD

**Issue by oreowork** [shadowjohn/mycomicbus_cli#3]
![image](https://user-images.githubusercontent.com/52243223/135944384-e888dd30-5903-461d-8c27-f9ab8c87f96f.png)

看來網站做了一些措施，我查了下，這次的網站url並沒有修改，可能是加密修改了。

**Comment by shadowjohn** [comment]
![image](https://user-images.githubusercontent.com/1788472/135951720-9d2addc3-ca47-4639-b386-fed5cabdf0b6.png)
修好了~再試看看
官方偷加了一行
(adsbygoogle = window.adsbygoogle || []).push({});

可能是跟廣告有關的吧
註解掉就沒事了

**Comment by oreowork** [comment]
> ![image](https://user-images.githubusercontent.com/1788472/135951720-9d2addc3-ca47-4639-b386-fed5cabdf0b6.png) 修好了~再試看看 官方偷加了一行 (adsbygoogle = window.adsbygoogle || []).push({});
> 
> 可能是跟廣告有關的吧 註解掉就沒事了

哇，你這回應也太快了，等下我測試後再提交測試截屏，謝謝你

**Comment by shadowjohn** [comment]
感謝您的回饋，現在很少看漫畫~
有啥Bug要靠您來發現了^^"
有其他站想爬也可以說，寫這個很有趣 :)

**Comment by oreowork** [comment]
> 感謝您的回饋，現在很少看漫畫~ 有啥Bug要靠您來發現了^^" 有其他站想爬也可以說，寫這個很有趣 :)

![image](https://user-images.githubusercontent.com/52243223/136020235-fdb6b0ad-f7af-4451-a899-b688412c0422.png)

抱歉今天有點忙。
剛剛測試了一下，問題完美解決。

我目前正在學習使用python selenium收集網站，這裡不方便說，哈哈

謝謝你
