### ISSUE TITLE
Bug回報

### ISSUE THREAD

**Issue by actcathorse** [shadowjohn/mycomicbus_cli#4]
作者您好，程式很好用，但有BUG回報，例如這種網址 https://a.twobili.com/online/new-7998.html?ch=2 ，程式會取得 https://a.twobili.com/online/new-7998.html?ch=1 的圖片網址，而不是第二集圖片的網址，在此告知，望您有空能修正，^_^，謝謝您！

**Comment by shadowjohn** [comment]
想...想不到居然有人在用....
謝謝您的回報，我晚上有空看看

**Comment by shadowjohn** [comment]
@actcathorse 
您好，謝謝您使用這個奇妙的漫畫下載機...
現在回頭去看，當然還真不知道嗑了什麼才寫出這樣的東西
到今天還能運作，居然還有人在用...
您提到的 bug 已修正
然後我加了多執行緒下載的參數，再試試吧^^
有任何問題歡迎再回饋給我
![image](https://github.com/user-attachments/assets/0ee6ca74-e26c-4327-8fe6-78b01edc5a08)
![image](https://github.com/user-attachments/assets/a26f0b30-5a78-4bfb-b4fe-9584cae998c5)

**Comment by actcathorse** [comment]
太感謝你囉！超棒的，有問題再來跟您回報，讚讚！

**Comment by shadowjohn** [comment]
祝您使用愉快
